/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyGreeting {
        /**
          * @default ''
         */
        "greeting": string;
    }
    interface MyInput {
        /**
          * @default ''
         */
        "msg": string;
    }
}
export interface MyInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyInputElement;
}
declare global {
    interface HTMLMyGreetingElement extends Components.MyGreeting, HTMLStencilElement {
    }
    var HTMLMyGreetingElement: {
        prototype: HTMLMyGreetingElement;
        new (): HTMLMyGreetingElement;
    };
    interface HTMLMyInputElementEventMap {
        "emit": string;
    }
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyInputElementEventMap>(type: K, listener: (this: HTMLMyInputElement, ev: MyInputCustomEvent<HTMLMyInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyInputElementEventMap>(type: K, listener: (this: HTMLMyInputElement, ev: MyInputCustomEvent<HTMLMyInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-greeting": HTMLMyGreetingElement;
        "my-input": HTMLMyInputElement;
    }
}
declare namespace LocalJSX {
    interface MyGreeting {
        /**
          * @default ''
         */
        "greeting"?: string;
    }
    interface MyInput {
        /**
          * @default ''
         */
        "msg"?: string;
        "onEmit"?: (event: MyInputCustomEvent<string>) => void;
    }

    interface MyGreetingAttributes {
        "greeting": string;
    }
    interface MyInputAttributes {
        "msg": string;
    }

    interface IntrinsicElements {
        "my-greeting": Omit<MyGreeting, keyof MyGreetingAttributes> & { [K in keyof MyGreeting & keyof MyGreetingAttributes]?: MyGreeting[K] } & { [K in keyof MyGreeting & keyof MyGreetingAttributes as `attr:${K}`]?: MyGreetingAttributes[K] } & { [K in keyof MyGreeting & keyof MyGreetingAttributes as `prop:${K}`]?: MyGreeting[K] };
        "my-input": Omit<MyInput, keyof MyInputAttributes> & { [K in keyof MyInput & keyof MyInputAttributes]?: MyInput[K] } & { [K in keyof MyInput & keyof MyInputAttributes as `attr:${K}`]?: MyInputAttributes[K] } & { [K in keyof MyInput & keyof MyInputAttributes as `prop:${K}`]?: MyInput[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-greeting": LocalJSX.IntrinsicElements["my-greeting"] & JSXBase.HTMLAttributes<HTMLMyGreetingElement>;
            "my-input": LocalJSX.IntrinsicElements["my-input"] & JSXBase.HTMLAttributes<HTMLMyInputElement>;
        }
    }
}
